// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL0dbkQgHjQnVcsvZgSftMiPRVsxA0gcU',
    appId: '1:628983044616:web:9baaf4b574be17a363cfbd',
    messagingSenderId: '628983044616',
    projectId: 'nutrimate-13aa4',
    authDomain: 'nutrimate-13aa4.firebaseapp.com',
    storageBucket: 'nutrimate-13aa4.firebasestorage.app',
    measurementId: 'G-MT08QE31EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzq5Rh6Wm2Nfc_jFH8qPik9uxiaF7LcQ0',
    appId: '1:628983044616:android:e14421b88297560e63cfbd',
    messagingSenderId: '628983044616',
    projectId: 'nutrimate-13aa4',
    storageBucket: 'nutrimate-13aa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiprh5lBFXDlOYnBOeP6VMKb1e5Jq6Hjk',
    appId: '1:628983044616:ios:57daa4584e28909063cfbd',
    messagingSenderId: '628983044616',
    projectId: 'nutrimate-13aa4',
    storageBucket: 'nutrimate-13aa4.firebasestorage.app',
    iosBundleId: 'com.example.foodTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiprh5lBFXDlOYnBOeP6VMKb1e5Jq6Hjk',
    appId: '1:628983044616:ios:57daa4584e28909063cfbd',
    messagingSenderId: '628983044616',
    projectId: 'nutrimate-13aa4',
    storageBucket: 'nutrimate-13aa4.firebasestorage.app',
    iosBundleId: 'com.example.foodTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL0dbkQgHjQnVcsvZgSftMiPRVsxA0gcU',
    appId: '1:628983044616:web:ca5a541b33f07f4c63cfbd',
    messagingSenderId: '628983044616',
    projectId: 'nutrimate-13aa4',
    authDomain: 'nutrimate-13aa4.firebaseapp.com',
    storageBucket: 'nutrimate-13aa4.firebasestorage.app',
    measurementId: 'G-MBCGXBM7M0',
  );
}
